version: "2"
services:
  app:
    build: ./app
    container_name: "appTweepy"
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    container_name: "dbTweepy"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  api:
    build: 
      context: ClientTweepy
      dockerfile: ClientTweepy/Dockerfile
    container_name: net-container
    environment:
      - "DB_PORT=3306"
    restart: always
    ports:
      - 8088:80  
  
  front:
    build: ./clientfront
    volumes:
      - ./volumefront:/var/www/html
    container_name: react-container    
    restart: always
    ports:
    - 80:3000

    depends_on:
    - db