global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    scrape_interval:  5s
    static_configs:
      - targets: ['api:80']

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
