CREATE DATABASE tweetpy CHARACTER SET utf8mb4;
use tweetpy;

CREATE TABLE IF NOT EXISTS TEST(
    `ID` VARCHAR(200) CHARACTER SET utf8,
);

CREATE TABLE IF NOT EXISTS tweepy(
                        ID_TWEET INTEGER AUTO_INCREMENT PRIMARY KEY,
						TWEET VARCHAR(900) NOT NULL,
						ID_USER INTEGER
						)




INSERT INTO last_tweets VALUES
    ('Tweet2022');




